# Generated by Django 3.2.4 on 2022-02-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_alter_registermodel_pic'),
        ('chat', '0002_auto_20220211_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='cname',
            field=models.CharField(default='sai', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authe.registermodel'),
        ),
    ]
