# Generated by Django 3.2.4 on 2022-02-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220211_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='cname',
        ),
    ]
