# Generated by Django 3.2.4 on 2022-02-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='pic',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
